CREATE DATABASE IF NOT EXISTS Firewatch DEFAULT CHARACTER SET utf8;

USE Firewatch;

DROP TABLE IF EXISTS Polygons;
CREATE TABLE Polygons(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Border VARCHAR(1024) NOT NULL,
  Center VARCHAR(64) NOT NULL
);

DROP TABLE IF EXISTS UserTypes;
CREATE TABLE UserTypes(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(64) NOT NULL
);

DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(64) NOT NULL,
  Password VARCHAR(256) NOT NULL,
  UserTypeId INT NOT NULL,
  CONSTRAINT FkUsers_UserTypeId FOREIGN KEY (UserTypeId) REFERENCES UserTypes (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS WeatherStations;
CREATE TABLE WeatherStations(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Coordinates VARCHAR(64) NOT NULL,
  Url VARCHAR(128),
  UserId INT NOT NULL,
  CONSTRAINT FkWeatherStations_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS January;
CREATE TABLE January(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkJanuary_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkJanuary_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS February;
CREATE TABLE February(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkFebruary_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkFebruary_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS March;
CREATE TABLE March(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkMarch_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkMarch_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS April;
CREATE TABLE April(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkApril_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkApril_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS May;
CREATE TABLE May(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkMay_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkMay_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS June;
CREATE TABLE June(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkJune_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkJune_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS July;
CREATE TABLE July(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkJuly_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkJuly_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS August;
CREATE TABLE August(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkAugust_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkAugust_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS September;
CREATE TABLE September(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkSeptember_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkSeptember_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS October;
CREATE TABLE October(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkOctober_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkOctober_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS November;
CREATE TABLE November(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkNovember_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkNovember_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS December;
CREATE TABLE December(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  WeatherStationId INT NOT NULL,
  Temperature FLOAT NOT NULL,
  Dew FLOAT NOT NULL,
  Precipitation FLOAT NOT NULL,
  Date DATE NOT NULL,
  UserId INT NOT NULL,
  CONSTRAINT FkDecember_WeatherStationId FOREIGN KEY (WeatherStationId) REFERENCES WeatherStations (Id) ON DELETE RESTRICT,
  CONSTRAINT FkDecember_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT
);